title: Rohit Pati
logo: /Pictures/IMG_4209.JPG
description: BE Mechanical Engineering | IOE Thapathali Campus, Tribhuvan University (2018-2023)
description: Mechanical Instructor | CTEVT, Balaju School of Engineering and Technology (2023-Active)
#show_downloads: true
theme: jekyll-theme-midnight
